# Crust OS — SDDM defaults to COSMIC Wayland session
[Autologin]
Session=cosmic
Relogin=false

[General]
HaltCommand=/usr/bin/systemctl poweroff
RebootCommand=/usr/bin/systemctl reboot
Numlock=on

[Theme]
Current=breeze
CursorTheme=breeze_cursors

[Users]
DefaultSession=cosmic.desktop
MaximumUid=65000
MinimumUid=1000

[Wayland]
SessionDir=/usr/share/wayland-sessions
EnableHiDPI=true
