#
# /etc/pacman.conf for Crust OS ISO build
#

[options]
HoldPkg       = pacman glibc
Architecture  = x86_64
Color
CheckSpace
VerbosePkgLists
ParallelDownloads = 5
SigLevel      = Required DatabaseOptional
LocalFileSigLevel = Optional

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[multilib]
Include = /etc/pacman.d/mirrorlist
