# Crust OS — Calamares settings
---
modules-search:
  - /usr/lib/calamares/modules
  - ./calamares/modules

sequence:
  - show:
      - welcome
      - locale
      - keyboard
      - partition
      - users
      - summary
  - exec:
      - partition
      - mount
      - unpackfs
      - machineid
      - fstab
      - locale
      - keyboard
      - localecfg
      - luksbootkeyfile
      - luksopenswaphookcfg
      - plymouthcfg
      - grubcfg
      - bootloader
      - systemd-boot
      - networkcfg
      - hwclock
      - services
      - users
      - displaymanager
      - dmconf
      - mkinicpio
      - initcpiocfg
      - initcpio-post
      - shellprocess
      - packages
      - removeuser
  - show:
      - finished

branding: crustos

prompt-install: true
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: false
