# Crust OS — global Wayland environment defaults
GBM_BACKEND=nvidia-drm
__GLX_VENDOR_LIBRARY_NAME=nvidia
WLR_NO_HARDWARE_CURSORS=1
QT_AUTO_SCREEN_SET_FACTOR=1
XDG_SESSION_TYPE=wayland
ELECTRON_OZONE_PLATFORM_HINT=auto
