# Crust OS — Bootloader configuration
---
loaderType: systemd-boot
bootloader: systemd-boot
efiBootloaderId: "Crust OS"
kernelLine: "quiet splash loglevel=3 rd.systemd.show_status=false rd.udev.log_priority=3 vt.global_cursor_default=0 i915.enable_psr=1 amdgpu.dcfeaturemask=0x2"
kernelParams:
  - quiet
  - splash
  - loglevel=3
  - rd.systemd.show_status=false
  - rd.udev.log_priority=3
  - vt.global_cursor_default=0
  - i915.enable_psr=1
  - amdgpu.dcfeaturemask=0x2
fallbackKernelParams:
  - nomodeset
  - loglevel=3
timeout: "0"
updateNvidiaGrub: false
