# Crust OS — mkinitcpio configuration (both kernels)
---
kernels:
  - linux-lts
  - linux-zen
config:
  MODULES: (btrfs)
  BINARIES: (/usr/bin/btrfs /usr/bin/snapper)
  HOOKS: (base udev autodetect modconf kms keyboard keymap consolefont block btrfs filesystems fsck)
