# Crust OS — Services to enable on target
---
services:
  - name: NetworkManager
    mandatory: true
  - name: bluetooth
    mandatory: false
  - name: iwd
    mandatory: false
  - name: sddm
    mandatory: true
  - name: fstrim.timer
    mandatory: false
  - name: pipewire.socket
    mandatory: false
  - name: pipewire-pulse.socket
    mandatory: false
  - name: wireplumber
    mandatory: false
  - name: snapper-timeline.timer
    mandatory: false
  - name: snapper-cleanup.timer
    mandatory: false
  - name: crust-snap-boot
    mandatory: false
  - name: crust-update.timer
    mandatory: false
